name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deoply.yml
      - tsconfig.json
      - package.json
      - src/index.ts

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: |
            # Deploy to Workers
            deploy
            # Deploy to Pages
            pages deploy pages --project-name filetas
